### ISSUE TITLE
Consider using Green Keeper

### ISSUE THREAD

**Issue by mcataford** [msrose/onetimer#3]
You should consider setting up [Green Keeper](https://greenkeeper.io). Word on the street, it's a hip new tool to keep your dependencies up to date. ~ 🚀

**Comment by mcataford** [comment]
![image](https://user-images.githubusercontent.com/6210361/63473586-00197780-c444-11e9-941c-b5ca6d30381c.png)

@msrose

**Comment by msrose** [comment]
RIP Greenkeeper it was good while it lasted 😢 Should probably enable dependabot at some point though 😛

**Comment by mcataford** [comment]
Or even more au goût du jour: Renovate. :)

**Comment by msrose** [comment]
Dang the PR grouping stuff looks cool, I'll have to give it a try somewhere 💯
